Meshes:
  - Name: 'RedBall'
    FbxPath: "/home/lprotche/Documents/research/autonomous_drone/drone/src/resources/images/PokemonGoBall.FBX"
    Location: "230 10 23"
    Rotation: "0 0 45"
    Scale: "0.3 0.3 0.3"
    SnapToGround: false
